//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using UniCloud.Domain.Model;

    /// <summary>
    /// 座级
    /// </summary>
    public class AcCategory : IntAggregateRoot
    {
        public AcCategory()
        {
            this.Guid = new Guid();
        }
        /// <summary>
        /// Guid
        /// </summary>
        public virtual Guid Guid
        {
            get;
            set;
        }

        /// <summary>
        /// 座级等级
        /// </summary>
        public virtual string Level
        {
            get;
            set;
        }

        /// <summary>
        /// 座级描述
        /// </summary>
        public virtual string Regional
        {
            get;
            set;
        }

    }
}

