//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using UniCloud.Domain;

    /// <summary>
    /// 配置
    /// </summary>
    public class AcConfig : IntEntity
    {
        public AcConfig()
        {
            //this.AcRegs = new HashSet<AcReg>();
            this.Guid = new Guid();
        }

        /// <summary>
        /// Guid
        /// </summary>
        public virtual Guid Guid
        {
            get; 
            set;
        }

        /// <summary>
        /// 机型名称
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

        /// <summary>
        /// 机型关键字
        /// </summary>
        public virtual int AcModelID
        {
            get;
            set;
        }

        /// <summary>
        /// AcModelGuid
        /// </summary>
        public virtual Guid AcModelGuid
        {
            get;
            set;
        }

        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

        /// <summary>
        /// 飞机最大滑行重量
        /// </summary>
        public virtual decimal MTW
        {
            get;
            set;
        }

        public virtual decimal BW
        {
            get;
            set;
        }

        /// <summary>
        /// 基本重量重心
        /// </summary>
        public virtual decimal BWF
        {
            get;
            set;
        }

        /// <summary>
        /// 基本重量
        /// </summary>
        public virtual decimal BWI
        {
            get;
            set;
        }

        public virtual decimal BEW
        {
            get;
            set;
        }

        /// <summary>
        /// 飞机最大起飞重量
        /// </summary>
        public virtual decimal MTOW
        {
            get;
            set;
        }

        /// <summary>
        /// 飞机最大着陆重量
        /// </summary>
        public virtual decimal MLW
        {
            get;
            set;
        }

        /// <summary>
        /// 飞机最大零燃油重量
        /// </summary>
        public virtual decimal MZFW
        {
            get;
            set;
        }

        /// <summary>
        /// 飞机最大可用燃油
        /// </summary>
        public virtual decimal MMFW
        {
            get;
            set;
        }

        /// <summary>
        /// 飞机最大商载
        /// </summary>
        public virtual decimal MCC
        {
            get;
            set;
        }

        //public virtual ICollection<AcReg> AcRegs
        //{
        //    get;
        //    set;
        //}

        //public virtual AcModel AcModel
        //{
        //    get;
        //    set;
        //}

        public override bool Equals(object obj)
        {
            if (!(obj is AcConfig))
                return false;
            var acConfig = obj as AcConfig;
            if (acConfig == null)
                return false;
            if (acConfig.Name.Equals(Name))
                return true;
            return false;
        }

        public override int GetHashCode()
        {
            return this.Name.GetHashCode();
        }

    }
}

