//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using UniCloud.Domain;

    /// <summary>
    /// 机型
    /// </summary>
    public class AcModel : IntEntity
    {
        public AcModel()
        {
            //this.AcRegs = new HashSet<AcReg>();
            this.AcConfigs = new HashSet<AcConfig>();
            this.Guid = new Guid();
        }

        /// <summary>
        /// Guid
        /// </summary>
        public virtual Guid Guid
        {
            get;
            set;
        }

        /// <summary>
        /// 名称
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

        /// <summary>
        /// 系列主键
        /// </summary>
        public virtual int AcTypeID
        {
            get;
            set;
        }

        /// <summary>
        /// AcTypeGuid
        /// </summary>
        public virtual Guid AcTypeGuid
        {
            get;
            set;
        }

        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

        //public virtual ICollection<AcReg> AcRegs
        //{
        //    get;
        //    set;
        //}

        public virtual ICollection<AcConfig> AcConfigs
        {
            get;
            set;
        }

        //public virtual AcType AcType
        //{
        //    get;
        //    set;
        //}

        public override bool Equals(object obj)
        {
            if (!(obj is AcModel))
                return false;
            var acModel = obj as AcModel;
            if (acModel == null)
                return false;
            if (acModel.Name.Equals(Name))
                return true;
            return false;
        }

        public override int GetHashCode()
        {
            return this.Name.GetHashCode();
        }

    }
}

