//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using UniCloud.Domain.Model;

    /// <summary>
    /// 飞机
    /// </summary>
    public class AcReg : IntAggregateRoot
    {
        public AcReg()
        {
            this.AcregLicenses = new HashSet<AcregLicense>();
            this.Guid = new Guid();
            this.AcConfigGuid = new Guid();
            this.AcModelGuid = new Guid();
            this.AcTypeGuid = new Guid();
            this.DecodeConfigGuid = new Guid();
        }
        /// <summary>
        /// Guid
        /// </summary>
        public virtual Guid Guid
        {
            get;
            set;
        }

        /// <summary>
        /// 机型外键
        /// </summary>
        public virtual int AcTypeID
        {
            get;
            set;
        }

        /// <summary>
        /// AcTypeGuid
        /// </summary>
        public virtual Guid AcTypeGuid
        {
            get;
            set;
        }

        public virtual string Owner
        {
            get;
            set;
        }

        /// <summary>
        /// 运营方
        /// </summary>
        public virtual string Operators
        {
            get;
            set;
        }

        /// <summary>
        /// 引进方式
        /// </summary>
        public virtual string ImportCategory
        {
            get;
            set;
        }

        /// <summary>
        /// 退出方式
        /// </summary>
        public virtual string ExportCategory
        {
            get;
            set;
        }

        /// <summary>
        /// 注册号
        /// </summary>
        public virtual string RegNumber
        {
            get;
            set;
        }

        /// <summary>
        /// 出厂序列号
        /// </summary>
        public virtual string Msn
        {
            get;
            set;
        }

        /// <summary>
        /// 运营状态
        /// </summary>
        public virtual bool IsOperation
        {
            get;
            set;
        }

        /// <summary>
        /// 创建日期
        /// </summary>
        public virtual DateTime CreateDate
        {
            get;
            set;
        }

        /// <summary>
        /// 出厂日期
        /// </summary>
        public virtual DateTime FactoryDate
        {
            get;
            set;
        }

        /// <summary>
        /// 引进日期
        /// </summary>
        public virtual DateTime ImportDate
        {
            get;
            set;
        }

        /// <summary>
        /// 注销日期
        /// </summary>
        public virtual DateTime? ExportDate
        {
            get;
            set;
        }

        /// <summary>
        /// 座位数
        /// </summary>
        public virtual int SeatingCapacity
        {
            get;
            set;
        }

        /// <summary>
        /// 商载量
        /// </summary>
        public virtual decimal CarryingCapacity
        {
            get;
            set;
        }

        public virtual int AcModelID
        {
            get;
            set;
        }

        /// <summary>
        /// AcModelGuid
        /// </summary>
        public virtual Guid AcModelGuid
        {
            get;
            set;
        }

        public virtual int AcConfigID
        {
            get;
            set;
        }

        /// <summary>
        /// AcConfigGuid
        /// </summary>
        public virtual Guid AcConfigGuid
        {
            get;
            set;
        }

        /// <summary>
        /// 译码配置
        /// </summary>
        public virtual int? DecodeConfigID
        {
            get;
            set;
        }

        /// <summary>
        /// DecodeConfigGuid
        /// </summary>
        public virtual Guid DecodeConfigGuid
        {
            get;
            set;
        }

        /// <summary>
        /// 发动机推力
        /// </summary>
        public virtual string EngineTr
        {
            get;
            set;
        }

        /// <summary>
        /// 标准时差
        /// </summary>
        public virtual int OffsetUTC
        {
            get;
            set;
        }

        /// <summary>
        /// QAR帧长
        /// </summary>
        public virtual int SubframeLenght
        {
            get;
            set;
        }

        public virtual ICollection<AcregLicense> AcregLicenses
        {
            get;
            set;
        }

        public override bool Equals(object obj)
        {
            if (!(obj is AcReg))
                return false;
            var acreg = obj as AcReg;
            if (acreg == null)
                return false;
            if (acreg.RegNumber.Equals(RegNumber))
                return true;
            return false;
        }

        public override int GetHashCode()
        {
            return RegNumber.GetHashCode();
        }
    }
}

