//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using UniCloud.Domain;

    /// <summary>
    /// 飞机证照
    /// </summary>
    public class LicenseType : IntAggregateRoot
    {
        public LicenseType()
        {
            //this.AcregLicenses = new HashSet<AcregLicense>();
            this.Guid = new Guid();
        }

        /// <summary>
        /// Guid
        /// </summary>
        public virtual Guid Guid
        {
            get;
            set;
        }

        public virtual string Type
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual bool HasFile
        {
            get;
            set;
        }

        //public virtual ICollection<AcregLicense> AcregLicenses
        //{
        //    get;
        //    set;
        //}

        public override bool Equals(object obj)
        {
            if (!(obj is LicenseType))
                return false;
            var licenseType = obj as LicenseType;
            if (licenseType == null)
                return false;
            if (licenseType.Type.Equals(Type))
                return true;
            return false;
        }

        public override int GetHashCode()
        {
            return Type.GetHashCode();
        }
    }
}

