//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
    using System;

    public class AcStructure : IntAggregateRoot
    {
        /// <summary>
        /// 飞机
        /// </summary>
        public virtual string Actype
        {
            get;
            set;
        }

        /// <summary>
        /// 机型
        /// </summary>
        public virtual string Acmodel
        {
            get;
            set;
        }

        public virtual string ReportNo
        {
            get;
            set;
        }

        /// <summary>
        /// 文件类型（结构/腐蚀）报告
        /// </summary>
        public virtual string ReportType
        {
            get;
            set;
        }

        /// <summary>
        /// 报告日期
        /// </summary>
        public virtual DateTime? ReportDate
        {
            get;
            set;
        }

        /// <summary>
        /// 损伤/腐蚀描述
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

        /// <summary>
        /// 是否保留
        /// </summary>
        public virtual string IsDefer
        {
            get;
            set;
        }

        public virtual string Acreg
        {
            get;
            set;
        }

        /// <summary>
        /// 技术评估
        /// </summary>
        public virtual string TecAss
        {
            get;
            set;
        }

        /// <summary>
        /// 处理结果
        /// </summary>
        public virtual string TreatResult
        {
            get;
            set;
        }

        /// <summary>
        /// 状态
        /// </summary>
        public virtual string Status
        {
            get;
            set;
        }

        /// <summary>
        /// 关闭日期
        /// </summary>
        public virtual DateTime? CloseDate
        {
            get;
            set;
        }

        /// <summary>
        /// 来源
        /// </summary>
        public virtual string Source
        {
            get;
            set;
        }

        /// <summary>
        /// 腐蚀级别
        /// </summary>
        public virtual string Level
        {
            get;
            set;
        }

        /// <summary>
        /// 修理期限
        /// </summary>
        public virtual string RepairDeadline
        {
            get;
            set;
        }
    }
}

