//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;

    /// <summary>
	/// ADSB 执行情况
	/// </summary>
    public class AdsbComply : IntAggregateRoot
	{
		/// <summary>
		/// 系列(10)
		/// </summary>
		public virtual string Actype
		{
			get;
			set;
		}

		/// <summary>
		/// 文件类型
		/// </summary>
		public virtual string FileType
		{                             
			get;                    
			set;                     
		}                             
                                      
		/// <summary>      
		/// 文件号               
		/// </summary>     
		public virtual string  FileNo
		{                             
			get;                    
			set;                     
		}                             
                                      
		/// <summary>      
		/// 文件版本            
		/// </summary>     
		public virtual string FileVersion
		{
			get;
			set;
		}

		/// <summary>
		/// 执行飞机
		/// </summary>
		public virtual string ComplyAc
		{
			get;
			set;
		}

		/// <summary>
		/// 执行状态
		/// </summary>
		public virtual string ComplyStatus
		{
			get;
			set;
		}

		/// <summary>
		/// 执行日期
		/// </summary>
		public virtual DateTime? ComplyDate
		{
			get;
			set;
		}

		/// <summary>
		/// 执行反馈
		/// </summary>
		public virtual string ComplyNotes
		{
			get;
			set;
		}

		/// <summary>
		/// 执行监控关闭情况
		/// </summary>
		public virtual string ComplyClose
		{
			get;
			set;
		}

		/// <summary>
		/// 执行费用
		/// </summary>
		public virtual decimal? ComFee
		{
			get;
			set;
		}

		/// <summary>
		/// 执行费用备注
		/// </summary>
		public virtual string ComFeeNotes
		{
			get;
			set;
		}

		/// <summary>
		/// 执行费用币种
		/// </summary>
		public virtual string ComFeeCurrency
		{
			get;
			set;
		}

        /// <summary>
        /// Adsb外键
        /// </summary>
        public virtual int AdsbID
        {
            get;
            set;
        }

        /// <summary>
        /// Adsb
        /// </summary>
        public virtual Adsb Adsb
        {
            get;
            set;
        }

	}
}

