//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using UniCloud.Domain.Events;

	/// <summary>
	/// 拆装指令
	/// </summary>
    public class CcOrder : IntAggregateRoot
	{
	    public CcOrder()
	    {
	        this.Ccins = new HashSet<Ccin>();
	        this.Ccouts = new HashSet<Ccout>();
	    }

		/// <summary>
		/// 指令号
		/// </summary>
		public virtual string OrderNo
		{
			get;
			set;
		}

		/// <summary>
		/// 拆装类型
		/// </summary>
		public virtual string Cctype
		{
			get;
			set;
		}

		/// <summary>
		/// 飞机
		/// </summary>
		public virtual string AcReg
		{
			get;
			set;
		}

		/// <summary>
		/// 交换飞机
		/// </summary>
        public virtual string SwapAcreg
		{
			get;
			set;
		}

		public virtual string RemReason
		{
			get;
			set;
		}

		/// <summary>
		/// 工作包号
		/// </summary>
		public virtual string WoNo
		{
			get;
			set;
		}

		/// <summary>
		/// 工作包项
		/// </summary>
		public virtual string WoItem
		{
			get;
			set;
		}

		/// <summary>
		/// 工作类型（工作包，NRC,故障单)
		/// </summary>
		public virtual string WoType
		{
			get;
			set;
		}

		public virtual DateTime UpdateDate
		{
			get;
			set;
		}

		public virtual string UpdateBy
		{
			get;
			set;
		}

		public virtual string State
		{
			get;
			set;
		}

	    public virtual string Operator
	    {
            get;
            set;
	    }

	    public virtual DateTime OperatDate
	    {
            get;
            set;
	    }

        /// <summary>
        /// 件号主键
        /// </summary>
        public virtual int? PnRegID
        {
            get;
            set;
        }

        /// <summary>
        /// 序号
        /// </summary>
        public virtual int? SnRegID
        {
            get;
            set;
        }

        public virtual ICollection<Ccout> Ccouts
		{
			get;
			set;
		}

        public virtual ICollection<Ccin> Ccins
		{
			get;
			set;
		}

        public void PublishCcOrderEvent(string acreg,DateTime operateDate,List<SnHistory> snHistorys,
            string swapAcreg=null)
        {
            RaiseEvent<CcOrderEvent>(new CcOrderEvent(this)
                                     {
                                         Acreg=acreg,OperateDate=operateDate,
                                         SnHistorys=snHistorys,
                                         SwapAcreg=swapAcreg
                                     });
        }

	}
}

