//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 附件时限
	/// </summary>
    public class CcpLimit : IntEntity
	{
		/// <summary>
		/// 组别
		/// </summary>
		public virtual string Ieam
		{
			get;
			set;
		}

		/// <summary>
		/// 范围最小值
		/// </summary>
		public virtual int? RangeMin
		{
			get;
			set;
		}

		/// <summary>
		/// 控制类型
		/// </summary>
		public virtual string ControlType
		{
			get;
			set;
		}

		/// <summary>
		/// 组内项号
		/// </summary>
		public virtual string ControlNo
		{
			get;
			set;
		}

		/// <summary>
		/// 发动机推力
		/// </summary>
		public virtual string EngineTli
		{
			get;
			set;
		}

		/// <summary>
		/// 时限单位
		/// </summary>
		public virtual string Unit
		{
			get;
			set;
		}

		/// <summary>
		/// 时限间隔
		/// </summary>
		public virtual int Interval
		{
			get;
			set;
		}

		/// <summary>
		/// 组内小组
		/// </summary>
		public virtual string ControlGroup
		{
			get;
			set;
		}

		/// <summary>
		/// 范围最大值
		/// </summary>
		public virtual int? RangeMax
		{
			get;
			set;
		}

		/// <summary>
		/// 范围类型
		/// </summary>
		public virtual string RangeType
		{
			get;
			set;
		}

		/// <summary>
		/// 到限工作
		/// </summary>
		public virtual string WorkScope
		{
			get;
			set;
		}

        public virtual int? WorkScopeID
        {
            get;
            set;
        }

		/// <summary>
		/// 执行策略
		/// </summary>
		public virtual string PolicyExec
		{
			get;
			set;
		}

		/// <summary>
		/// 参考材料
		/// </summary>
		public virtual string Source
		{
			get;
			set;
		}

		public virtual string Notes
		{
			get;
			set;
		}

		public virtual WorkScope WorkScopeItem
		{
			get;
			set;
		}

        public virtual int CcpMainID
        {
            get; 
            set;
        }
         
	}
}

