//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 附件项
	/// </summary>
    public class CcpMain : IntAggregateRoot
	{
	    public CcpMain()
	    {
	        CcpLimits = new HashSet<CcpLimit>();
	        CcpPns = new HashSet<CcpPn>();
	    }

	    /// <summary>
		/// 附件项号
		/// </summary>
		public virtual string ItemNo
		{
			get;
			set;
		}

		/// <summary>
		/// 机型
		/// </summary>
		public virtual string AcType
		{
			get;
			set;
		}



		/// <summary>
		/// 章节
		/// </summary>
        public virtual string Ata
		{
			get;
			set;
		}



		/// <summary>
		/// 描述
		/// </summary>
		public virtual string Description
		{
			get;
			set;
		}

		/// <summary>
		/// 是否寿控
		/// </summary>
		public virtual bool IsLife
		{
			get;
			set;
		}

		/// <summary>
		/// 状态
		/// </summary>
		public virtual string State
		{
			get;
			set;
		}

		/// <summary>
		/// 版本
		/// </summary>
		public virtual int Version
		{
			get;
			set;
		}

		/// <summary>
		/// 上级项号
		/// </summary>
		public virtual string NhItemNo
		{
			get;
			set;
		}

		public virtual string Updateby
		{
			get;
			set;
		}

		public virtual DateTime UpdateTime
		{
			get;
			set;
		}

        public virtual ICollection<CcpLimit> CcpLimits
		{
			get;
			set;
		}

        public virtual ICollection<CcpPn> CcpPns
		{
			get;
			set;
		}

	}
}

