//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 滑油添加记录
	/// </summary>
    public class OilAnalysis : IntAggregateRoot
	{
        /// <summary>
        /// 监控日期/日历日
        /// </summary>
        public virtual DateTime FlightDate { get; set; }
        /// <summary>
        /// 发动机件号
        /// </summary>
        public virtual string Pn { get; set; }

        /// <summary>
        /// 发动机序号
        /// </summary>
        public virtual string Sn { get; set; }

        /// <summary>
		/// 飞机号
		/// </summary>
		public virtual string AcReg{get;set;}
        /// <summary>
		/// 飞机序列号
		/// </summary>
		public virtual string Msn{get;set;}
        /// <summary>
        /// 章节
        /// </summary>
        public virtual string Ata { get; set; }

        /// <summary>
        /// 区域
        /// </summary>
        public virtual string Zone { get; set; }

        /// <summary>
        /// 安装位置
        /// </summary>
        public virtual string Position { get; set; }

        /// <summary>
		/// 自修理至今添加量总量TQSR
		/// </summary>
		public virtual decimal Tqsr{get;set;}

        /// <summary>
        /// 自修理至今飞行时间
		/// </summary>
        public virtual decimal Tsr { get; set; }

        /// <summary>
        /// 累积消耗率
        /// </summary>
        public virtual decimal? Toc { get; set; }
        /// <summary>
        /// 预留
        /// </summary>
        public virtual decimal? Tocn { get; set; }
        /// <summary>
        /// 间隔消耗率
        /// </summary>
        public virtual decimal? Ioc { get; set; }
        /// <summary>
        /// 间隔累积率增量
        /// </summary>
        public virtual decimal? Ioca { get; set; }
        /// <summary>
        /// 预留
        /// </summary>
        public virtual decimal? Iocn { get; set; }
        /// <summary>
        /// 3天滚动累积消耗率
        /// </summary>
        public virtual decimal? Aoc3 { get; set; }
        /// <summary>
        /// 7天滚动累积消耗率
        /// </summary>
        public virtual decimal? Aoc7 { get; set; }
        /// <summary>
        /// 预留
        /// </summary>
        public virtual decimal? Aocn { get; set; }
        /// <summary>
		/// 警告标识
		/// </summary>
		public virtual string WarnTag{get;set;}
        /// <summary>
        /// 备注
        /// </summary>
        public virtual string Notes { get; set; }
	}
}

