//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 滑油添加记录
	/// </summary>
	public class OilHistory:IntAggregateRoot
	{

        /// <summary>
		/// 飞机号
		/// </summary>
		public virtual string AcReg{get;set;}
        /// <summary>
		/// 飞机序列号
		/// </summary>
		public virtual string Msn{get;set;}
		
        /// <summary>
		/// 飞行日期
		/// </summary>
        public virtual DateTime FlightDate { get; set; }

        /// <summary>
		/// 飞行日志号
		/// </summary>
		public virtual string FlLogno{get;set;}

        /// <summary>
		/// 航段号
		/// </summary>
		public virtual string FlLegno{get;set;}

        /// <summary>
		/// 航前添加量
		/// </summary>
		public virtual decimal UpliftDer{get;set;}

        /// <summary>
		/// 航后添加量
		/// </summary>
        public virtual decimal UpliftArr { get; set; }

        /// <summary>
		/// 发动机件号
		/// </summary>
		public virtual string Pn{get;set;}

        /// <summary>
		/// 发动机序号
		/// </summary>
		public virtual string Sn{get;set;}

        /// <summary>
		/// 章节
		/// </summary>
		public virtual string Ata{get;set;}

        /// <summary>
		/// 区域
		/// </summary>
		public virtual string Zone{get;set;}

        /// <summary>
		/// 安装位置
		/// </summary>
		public virtual string Position{get;set;}

        /// <summary>
		/// TSN
		/// </summary>
        public virtual decimal Tsn { get; set; }

        /// <summary>
		/// Csn
		/// </summary>
        public virtual decimal Csn { get; set; }

        /// <summary>
        /// FH
        /// </summary>
        public virtual decimal Fh { get; set; }

        /// <summary>
        /// CY
        /// </summary>
        public virtual decimal Cy { get; set; }

        /// <summary>
		/// 飞行日期
		/// </summary>
		public virtual DateTime UpdateDate{get;set;}

        /// <summary>
		/// 备注
		/// </summary>
		public virtual string Notes{get;set;}
        /// <summary>
        /// 最近一次安装日期
        /// </summary>
        public virtual string InstalDate { get; set; }
      
	}
}

