//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 
//     如果重新生成代码，将丢失对此文件所做的更改。 
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 件号
	/// </summary>
	public class PnReg:IntAggregateRoot
	{
        public PnReg()
        {
            //this.CcpPns=new HashSet<CcpPn>();
        }
		/// <summary>
		/// 厂家件号
		/// </summary>
		public virtual string Pn
		{
			get;
			set;
		}

		/// <summary>
		/// 件号类型
		/// </summary>
		public virtual string PnClass
		{
			get;
			set;
		}

		/// <summary>
		/// 章节
		/// </summary>
		public virtual string Ata
		{
			get;
			set;
		}

		/// <summary>
		/// 首选供应商
		/// </summary>
		public virtual string Vendor
		{
			get;
			set;
		}

		/// <summary>
		/// 更新时间
		/// </summary>
		public virtual DateTime UpdateTime
		{
			get;
			set;
		}

		/// <summary>
		/// 更新人
		/// </summary>
		public virtual string Updateby
		{
			get;
			set;
		}

		/// <summary>
		/// 状态
		/// </summary>
		public virtual string State
		{
			get;
			set;
		}

		/// <summary>
		/// 规范件号
		/// </summary>
		public virtual string SpecPn
		{
			get;
			set;
		}

        /// <summary>
        /// 是否寿控
        /// </summary>
	    public virtual bool IsLife
	    {
            get;
            set;
	    }

        /// <summary>
        /// 描述
        /// </summary>
	    public virtual string Description
	    {
            get;
            set;
	    }

        /// <summary>
        /// 转化率
        /// </summary>
        public virtual int? TrainRate
        {
            get;
            set;
        }

        /// <summary>
        /// 发动机EGT裕度下限
        /// </summary>
        public virtual decimal? EGTLimit
        {
            get;
            set;
        }

        /// <summary>
        /// AOC3
        /// </summary>
        public virtual decimal? AOC3
        {
            get;
            set;
        }
        /// <summary>
        /// AOC7
        /// </summary>
        public virtual decimal? AOC7
        {
            get;
            set;
        }
        /// <summary>
        /// IOC
        /// </summary>
        public virtual decimal? IOC
        {
            get;
            set;
        }
        /// <summary>
        /// IOCA
        /// </summary>
        public virtual decimal? IOCA
        {
            get;
            set;
        }
	}
}

