//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// SCN飞机
	/// </summary>
	public class ScnAcorder:IntEntity
	{
		public virtual string AcOrder
		{
			get;
			set;
		}

		public virtual string AcOrderItem
		{
			get;
			set;
		}

		public virtual string Notes
		{
			get;
			set;
		}

        /// <summary>
        /// ScnMain外键
        /// </summary>
        public virtual int ScnMainID
        {
            get;
            set;
        }

        /// <summary>
        /// Scn价格
        /// </summary>
        public virtual decimal?  Price
        {
            get;
            set;
        }

        /// <summary>
        /// MSN
        /// </summary>
        public virtual string MSN
        {
            get;
            set;
        }

        /// <summary>
        /// 批次
        /// </summary>
        public virtual string CSCNumber
        {
            get;
            set;
        }

        //public ScnMain ScnMain
        //{
        //    get;
        //    set;
        //}

	}
}

