//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// SCN明细
	/// </summary>
	public class ScnItem:IntEntity
	{
		/// <summary>
		/// 附件项
		/// </summary>
		public virtual int ScnMainID
		{
			get;
			set;
		}

		/// <summary>
		/// 项次
		/// </summary>
		public virtual int ItemNo
		{
			get;
			set;
		}

		/// <summary>
		/// 件号（可空）
		/// </summary>
		public virtual int? PnRegID
		{
			get;
			set;
		}

        /// <summary>
        /// ATA章节
        /// </summary>
		public virtual int AtaID
		{
			get;
			set;
		}

        /// <summary>
        /// ATA章节GUID
        /// </summary>
	    public virtual Guid AtaGuid
	    {
            get;
            set;
	    }

		/// <summary>
		/// 件号
		/// </summary>
		public virtual string Pn
		{
			get;
			set;
		}

		/// <summary>
		/// 产品描述
		/// </summary>
		public virtual string Description
		{
			get;
			set;
		}

		/// <summary>
		/// 供应商
		/// </summary>
		public virtual string Vendor
		{
			get;
			set;
		}

		public virtual string Notes
		{
			get;
			set;
		}

		/// <summary>
		/// 数量
		/// </summary>
		public virtual int Qty
		{
			get;
			set;
		}

		/// <summary>
		/// 单价
		/// </summary>
        public virtual decimal Price
		{
			get;
			set;
		}

		/// <summary>
		/// 总价
		/// </summary>
        public virtual decimal TotalPrice
		{
			get;
			set;
		}

		/// <summary>
		/// 币种
		/// </summary>
		public virtual string Currency
		{
			get;
			set;
		}

        //public ScnMain ScnMain
        //{
        //    get;
        //    set;
        //}
	}
}

