//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// SCN
	/// </summary>
	public class ScnMain :IntAggregateRoot
	{
	    public ScnMain()
	    {
	        this.ScnItems = new HashSet<ScnItem>();
	        this.ScnAcorders = new HashSet<ScnAcorder>();
            //this.WfHistorys = new HashSet<WfHistory>();
	    }
		public virtual string ScnNo
		{
			get;
			set;
		}

		public virtual int AcTypeID
		{
			get;
			set;
		}

	    public virtual Guid AcTypeGuid
	    {
            get;
            set;
	    }

		public virtual int AcModelID
		{
			get;
			set;
		}

	    public virtual Guid AcModelGuid
	    {
            get;
            set;
	    }

		public virtual string Version
		{
			get;
			set;
		}

		public virtual string State
		{
			get;
			set;
		}

        /// <summary>
        /// SCN描述
        /// </summary>
		public virtual string Description
		{
			get;
			set;
		}

        /// <summary>
        /// 类型
        /// </summary>
        public virtual string ScnType
        {
            get;
            set;
        }

        /// <summary>
        /// 关闭情况
        /// </summary>
        public virtual int CloseSituation
        {
            get;
            set;
        }

        /// <summary>
        /// 关闭时间
        /// </summary>
        public virtual DateTime? ColseTime
        {
            get;
            set;
        }

        /// <summary>
        /// 创建人
        /// </summary>
        public virtual string CreateUser
        {
            get;
            set;
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateTime
        {
            get;
            set;
        }

        /// <summary>
        /// 标题
        /// </summary>
        public virtual string ScnTitle
	    {
            get;
            set;
	    }

        /// <summary>
        /// Mod号
        /// </summary>
        public virtual string ModName
        {
            get;
            set;
        }


        /// <summary>
        /// 金额
        /// </summary>
        public virtual decimal Amount
        {
            get;
            set;
        }


        /// <summary>
        /// 附件关联ID
        /// </summary>
        public virtual Guid? DocumentID
        {
            get;
            set;
        }

        /// <summary>
        /// ATA号
        /// </summary>
        public virtual string Ata
        {
            get;
            set;
        }

        /// <summary>
        /// 关联MSN的飞机
        /// </summary>
        public virtual string MoneyOnMsn
        {
            get;
            set;
        }

        /// <summary>
        /// 关联部门
        /// </summary>
        public virtual string Organization
        {
            get;
            set;
        }

        /// <summary>
        /// 审核状态
        /// </summary>
        public virtual string VerifyStatus
        {
            get;
            set;
        }

        #region 导航属性
        public virtual ICollection<ScnItem> ScnItems
		{
			get;
			set;
		}

        public virtual ICollection<ScnAcorder> ScnAcorders
		{
			get;
			set;
		}

        //public virtual ICollection<WfHistory> WfHistorys
        //{
        //    get;
        //    set;
        //}
        #endregion

    }
}

