//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 部件历史信息
	/// </summary>
	public class SnHistory:IntAggregateRoot
	{
        public SnHistory()
        {
            this.SnHistoryUnits=new HashSet<SnHistoryUnit>();
        }
		/// <summary>
		/// SN组件
		/// </summary>
		public virtual int SnRegID
		{
			get;
			set;
		}
        /// <summary>
        /// 上级序号
        /// </summary>
        public virtual int? NhSnRegID
        {
            get;
            set;
        }
        public virtual int? RootSnRegID
        {
            get;
            set;
        }

        //5、拆装记录，只展示履历表中的拆下、装上记录。
        //   展示列排序：操作（拆下/装上）、拆装日期、飞机、章节、位置、推力、相关指令 相关附件（初始文件和证书）。
        //6、送修记录，只展示履历表中的送修记录。
        //   展示列排序：操作（修理级别）、修理日期、修理厂商、工作范围、相关指令 相关附件（初始文件和证书）
        //7、租赁记录，只展示履历表中的租赁记录。
        //   展示列排序：操作（租入/租出）、交付日期、出租方/承租方、租期、租金、小时费率、储备金、交付地点、相关指令、相关附件（初始文件和证书）。
        //字段合并：操作、操作日期、来源方（飞机/厂商）、章节、交接位置（交付地点/位置信息）、备注（推力/工作范围/租期、租金、小时费率、储备金、）相关指令、相关附件。

        /// <summary>
        /// 操作（拆下/装上）（修理级别）（租入/租出）
        /// </summary>
        public virtual string Active
        {
            get;
            set;
        }
        /// <summary>
        /// 发生日期 拆装日期 修理日期 交付日期
        /// </summary>
        public virtual DateTime ActiveDate
        {
            get;
            set;
        }
		/// <summary>
		/// 飞机、修理厂商、出租方/承租方
		/// </summary>
        public virtual string Source
		{
			get;
			set;
		}
        /// <summary>
        /// ATA章节组件
        /// </summary>
        public virtual string Ata
        {
            get;
            set;
        }
		/// <summary>
		/// 位置信息、交付地点
		/// </summary>
		public virtual string Position
		{
			get;
			set;
		}
        /// <summary>
        /// 备注（推力/工作范围/租期、租金、小时费率、储备金、）
        /// </summary>
        public virtual string Note
        {
            get;
            set;
        }
        /// <summary>
        /// 相关指令
        /// </summary>
        public virtual string Orderno
        {
            get;
            set;
        }

		public virtual SnReg SnReg
		{
			get;
			set;
		}
        public virtual SnReg NhSnReg
        {
            get;
            set;
        }

        public virtual ICollection<SnHistoryUnit> SnHistoryUnits
		{
			get;
			set;
		}

	}
}

