//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 序号件历史时间
	/// </summary>
	public class SnHistoryUnit:IntEntity
	{
		/// <summary>
		/// 部件历史ID
		/// </summary>
		public virtual int SnHistoryID
		{
			get;
			set;
		}

		/// <summary>
		/// 控制单位
		/// </summary>
		public virtual string Unit
		{
			get;
			set;
		}

		/// <summary>
		/// 
		/// </summary>
		public virtual Decimal USO
		{
			get;
			set;
		}

		/// <summary>
		/// 备用1
		/// </summary>
		public virtual Decimal USN
		{
			get;
			set;
		}

		/// <summary>
		/// 备用2
		/// </summary>
		public virtual Decimal USR
		{
			get;
			set;
		}

        /// <summary>
        /// 备用3
        /// </summary>
        public virtual Decimal USI
        {
            get;
            set;
        }

        ///// <summary>
        ///// 导航
        ///// </summary>
        //public virtual IntUnit Iunit
        //{
        //    get;
        //    set;
        //}
	}
}

