//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 
//     如果重新生成代码，将丢失对此文件所做的更改。 
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 序号件
	/// </summary>
	public class SnReg:IntAggregateRoot
	{
	    public SnReg()
	    {
	        this.EgtMargins = new HashSet<EgtMargin>();
	    }

        #region 一般属性

        /// <summary>
		/// PN ID
		/// </summary>
		public virtual int PnRegID
		{
			get;
			set;
		}
        /// <summary>
        /// 上级序号
        /// </summary>
        public virtual int? NhSnRegID
        {
            get;
            set;
        }

        public virtual int? RootSnRegID
        {
            get;
            set;
        }
		/// <summary>
		/// 序号
		/// </summary>
		public virtual string Sn
		{
			get;
			set;
		}

	    public virtual string Ac
	    {
            get;
            set;
	    }

	    public virtual string Ata
	    {
            get;
            set;
	    }

		/// <summary>
		/// 安装位置描述
		/// </summary>
		public virtual string Position
		{
			get;
			set;
		}

		/// <summary>
		/// 最近一次安装日期
		/// </summary>
		public virtual DateTime InstallDate
		{
			get;
			set;
		}

		/// <summary>
		/// 备注
		/// </summary>
		public virtual string Note
		{
			get;
			set;
		}

		/// <summary>
		/// 状态
		/// </summary>
		public virtual string Avail
		{
			get;
			set;
		}

		public virtual string Zone
		{
			get;
			set;
		}

        /// <summary>
        /// 推力
        /// </summary>
        public virtual string EngineTli
        {
            get;
            set;
        }

        /// <summary>
        ///  拆下时间
        /// </summary>
        public virtual DateTime? RemoveDate
        {
            get;
            set;
        }

        /// <summary>
        ///  送修时间
        /// </summary>
        public virtual DateTime? RepairDate
        {
            get;
            set;
        }

        /// <summary>
        ///  所有人
        /// </summary>
        public virtual string Owner
        {
            get;
            set;
        }

        /// <summary>
        ///  出租人
        /// </summary>
        public virtual string Leaser
        {
            get;
            set;
        }

        /// <summary>
        ///  属性
        /// </summary>
        public virtual string Propertys
        {
            get;
            set;
        }
        /// <summary>
        ///  修理间隔
        /// </summary>
        public virtual string Interval
        {
            get;
            set;
        }

        /// <summary>
        /// 是否同步AMASIS Y/N
        /// </summary>
        public virtual string SyncAMASIS
        {
            get;
            set;
        }

        /// <summary>
        /// 当前Egtm裕度
        /// </summary>
        public virtual decimal? Egtm
        {
            get;
            set;
        }
        #endregion

        #region 导航属性
        /// <summary>
        /// EGT裕度
        /// </summary>
        public virtual ICollection<EgtMargin> EgtMargins
        {
            get;
            set;
        }

        public virtual PnReg PnReg
        {
            get;
            set;
        }

        #endregion

        #region 虚拟属性 监控到期算法特用
        public virtual String PnClass
        {
            get;
            set;
        }
        public virtual int? TrainRate
        {
            get;
            set;
        }
        public virtual String RootPnClass
        {
            get;
            set;
        }
        public virtual SnHistory snHistory
        {
            get;
            set;
        }

        public virtual SnHistory ccHistory
        {
            get;
            set;
        }

        #endregion
    }
}

