//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 工作代码
	/// </summary>
	public class WorkScope:IntAggregateRoot
	{
		public virtual string Scope
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual string ShortName
		{
			get;
			set;
		}

		public virtual string Type
		{
			get;
			set;
		}
	}
}

