//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 装上信息
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class CcinDataObject
    {

        public CcinDataObject()
        {
        }

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 件号主键
        /// </summary>
        [DataMember]
        public virtual int PnRegID { get; set; }

        /// <summary>
        /// 序号主键
        /// </summary>
        [DataMember]
        public virtual int SnRegID { get; set; }

        /// <summary>
        /// 章节
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 属性
        /// </summary>
        [DataMember]
        public virtual string Propertys { get; set; }

        /// <summary>
        /// 区域
        /// </summary>
        [DataMember]
        public virtual string Zone { get; set; }

        /// <summary>
        /// 顺序号(下级件排序)
        /// </summary>
        [DataMember]
        public virtual int Seq { get; set; }

        /// <summary>
        /// 顶级序号
        /// </summary>
        [DataMember]
        public virtual int? RootSnRegID { get; set; }

        /// <summary>
        /// 上级序号
        /// </summary>
        [DataMember]
        public virtual int? NhSnRegID { get; set; }

        /// <summary>
        /// 推力
        /// </summary>
        [DataMember]
        public virtual string EngineTli { get; set; }

        /// <summary>
        /// CcOrder外键
        /// </summary>
        [DataMember]
        public virtual int CcOrderID { get; set; }

        //[DataMember]
        //public CcOrderDataObject CcOrder
        //{
        //    get;
        //    set;
        //}

        /// <summary>
        /// 修理间隔 小时
        /// </summary>
        [DataMember]
        public virtual int? FhInterval
        {
            get;
            set;
        }

        /// <summary>
        /// 修理间隔 循环
        /// </summary>
        [DataMember]
        public virtual int? CyInterval
        {
            get;
            set;
        }
        [DataMember]
        public virtual Decimal Tsn { get; set; }
        [DataMember]
        public virtual Decimal Tso { get; set; }
        [DataMember]
        public virtual Decimal Tsr { get; set; }
        [DataMember]
        public virtual Decimal Csn { get; set; }
        [DataMember]
        public virtual Decimal Cso { get; set; }
        [DataMember]
        public virtual Decimal Csr { get; set; }   

    }

    [CollectionDataContract]
    public class CcinDataObjectList : BaseDataObjectList<CcinDataObject>
    {
    }

    /// <summary>
    /// CcinResultData
    /// </summary>
    [DataContractAttribute(Name = "CcinResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (CcinResultData))]
    public class CcinResultData : ResultData<CcinDataObject>
    {
    }

    /// <summary>
    /// CcinWithPagination
    /// </summary>
    [KnownType(typeof (CcinWithPagination))]
    public class CcinWithPagination : BaseDataObjectListWithPagination<CcinDataObject>
    {
    }
}

