//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 拆装指令
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class CcOrderDataObject
    {
        public CcOrderDataObject()
        {
            this.Ccins = new CcinDataObjectList();
            this.Ccouts = new CcoutDataObjectList();
        }

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 指令号
        /// </summary>
        [DataMember]
        public virtual string OrderNo { get; set; }

        /// <summary>
        /// 拆装类型
        /// </summary>
        [DataMember]
        public virtual string Cctype { get; set; }

        /// <summary>
        /// 飞机
        /// </summary>
        [DataMember]
        public virtual string AcReg { get; set; }


        /// <summary>
        /// 交换飞机
        /// </summary>
        [DataMember]
        public virtual string SwapAcreg { get; set; }

        [DataMember]
        public virtual string RemReason { get; set; }

        /// <summary>
        /// 工作包号
        /// </summary>
        [DataMember]
        public virtual string WoNo { get; set; }

        /// <summary>
        /// 工作包项
        /// </summary>
        [DataMember]
        public virtual string WoItem { get; set; }

        /// <summary>
        /// 工作类型（工作包，NRC,故障单)
        /// </summary>
        [DataMember]
        public virtual string WoType { get; set; }

        [DataMember]
        public virtual DateTime UpdateDate { get; set; }

        [DataMember]
        public virtual string UpdateBy { get; set; }

        [DataMember]
        public virtual string State { get; set; }

        /// <summary>
        /// 操作人
        /// </summary>
        [DataMember]
        public virtual string Operator { get; set; }

        /// <summary>
        /// 操作时间
        /// </summary>
        [DataMember]
        public virtual DateTime OperatDate { get; set; }

        [DataMember]
        public virtual CcoutDataObjectList Ccouts { get; set; }

        [DataMember]
        public virtual CcinDataObjectList Ccins { get; set; }

        /// <summary>
        /// 件号主键
        /// </summary>
        [DataMember]
        public virtual int? PnRegID{ get; set; }

        /// <summary>
        /// 序号
        /// </summary>
        [DataMember]
        public virtual int? SnRegID {get; set; }

    }

    [CollectionDataContract]
    public class CcOrderDataObjectList : BaseDataObjectList<CcOrderDataObject>
    {
    }

    /// <summary>
    /// CcOrderResultData
    /// </summary>
    [DataContractAttribute(Name = "CcOrderResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (CcOrderResultData))]
    public class CcOrderResultData : ResultData<CcOrderDataObject>
    {
    }

    /// <summary>
    /// CcOrderWithPagination
    /// </summary>
    [KnownType(typeof (CcOrderWithPagination))]
    public class CcOrderWithPagination : BaseDataObjectListWithPagination<CcOrderDataObject>
    {
    }
}

