//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 拆下信息
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class CcoutDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 件号主键
        /// </summary>
        [DataMember]
        public virtual int PnRegID { get; set; }


        /// <summary>
        /// 序号主键
        /// </summary>
        [DataMember]
        public virtual int SnRegID { get; set; }

        /// <summary>
        /// 章节
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 位置
        /// </summary>
        [DataMember]
        public virtual string Position { get; set; }

        /// <summary>
        /// 区域
        /// </summary>
        [DataMember]
        public virtual string Zone { get; set; }

        /// <summary>
        /// 顺序号(下级件排序)
        /// </summary>
        [DataMember]
        public virtual int Seq { get; set; }

        /// <summary>
        /// 顶级序号
        /// </summary>
        [DataMember]
        public virtual int? RootSnRegID { get; set; }

        /// <summary>
        /// 上级序号
        /// </summary>
        [DataMember]
        public virtual int? NhSnRegID { get; set; }

        /// <summary>
        /// 非计划拆下
        /// </summary>
        [DataMember]
        public virtual bool UnScheduled { get; set; }

        /// <summary>
        /// CcOrder外键
        /// </summary>
        [DataMember]
        public virtual int CcOrderID { get; set; }

        /// <summary>
        /// 是否要求索赔
        /// </summary>
        [DataMember]
        public virtual bool IsClaim   { get; set;}

        //[DataMember]
        //public CcOrderDataObject CcOrder
        //{
        //    get;
        //    set;
        //}

    }

    [CollectionDataContract]
    public class CcoutDataObjectList : BaseDataObjectList<CcoutDataObject>
    {
    }

    /// <summary>
    /// CcoutResultData
    /// </summary>
    [DataContractAttribute(Name = "CcoutResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (CcoutResultData))]
    public class CcoutResultData : ResultData<CcoutDataObject>
    {
    }

    /// <summary>
    /// CcoutWithPagination
    /// </summary>
    [KnownType(typeof (CcoutWithPagination))]
    public class CcoutWithPagination : BaseDataObjectListWithPagination<CcoutDataObject>
    {
    }
}
