//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 附件时限
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class CcpLimitDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 组别
        /// </summary>
        [DataMember]
        public virtual string Ieam { get; set; }

        /// <summary>
        /// 范围最小值
        /// </summary>
        [DataMember]
        public virtual int? RangeMin { get; set; }

        /// <summary>
        /// 控制类型
        /// </summary>
        [DataMember]
        public virtual string ControlType { get; set; }

        /// <summary>
        /// 组内项号
        /// </summary>
        [DataMember]
        public virtual string ControlNo { get; set; }

        /// <summary>
        /// 发动机推力
        /// </summary>
        [DataMember]
        public virtual string EngineTli { get; set; }

        /// <summary>
        /// 时限单位
        /// </summary>
        [DataMember]
        public virtual string Unit { get; set; }

        /// <summary>
        /// 时限间隔
        /// </summary>
        [DataMember]
        public virtual int Interval { get; set; }

        /// <summary>
        /// 组内小组
        /// </summary>
        [DataMember]
        public virtual string ControlGroup { get; set; }

        /// <summary>
        /// 范围最大值
        /// </summary>
        [DataMember]
        public virtual int? RangeMax { get; set; }

        /// <summary>
        /// 范围类型
        /// </summary>
        [DataMember]
        public virtual string RangeType { get; set; }

        /// <summary>
        /// 到限工作
        /// </summary>
        [DataMember]
        public virtual string WorkScope { get; set; }

        [DataMember]
        public virtual int? WorkScopeID { get; set; }

        /// <summary>
        /// 执行策略
        /// </summary>
        [DataMember]
        public virtual string PolicyExec { get; set; }

        /// <summary>
        /// 参考材料
        /// </summary>
        [DataMember]
        public virtual string Source { get; set; }

        [DataMember]
        public virtual string Notes { get; set; }

        [DataMember]
        public virtual WorkScopeDataObject WorkScopeItem { get; set; }

        [DataMember]
        public virtual int CcpMainID { get; set; }

    }

    [CollectionDataContract]
    public class CcpLimitDataObjectList : BaseDataObjectList<CcpLimitDataObject>
    {
    }

    /// <summary>
    /// CcpLimitResultData
    /// </summary>
    [DataContractAttribute(Name = "CcpLimitResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (CcpLimitResultData))]
    public class CcpLimitResultData : ResultData<CcpLimitDataObject>
    {
    }

    /// <summary>
    /// CcpLimitWithPagination
    /// </summary>
    [KnownType(typeof (CcpLimitWithPagination))]
    public class CcpLimitWithPagination : BaseDataObjectListWithPagination<CcpLimitDataObject>
    {
    }
}