//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 附件项
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class CcpMainDataObject
    {
        public CcpMainDataObject()
        {
            this.CcpLimits = new CcpLimitDataObjectList();
            this.CcpPns = new CcpPnDataObjectList();
            this.WfHistorys = new WfHistoryDataObjectList();
        }

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 附件项号
        /// </summary>
        [DataMember]
        public virtual string ItemNo { get; set; }

        /// <summary>
        /// 机型
        /// </summary>
        [DataMember]
        public virtual string AcType { get; set; }

        /// <summary>
        /// 章节
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [DataMember]
        public virtual string Description { get; set; }

        /// <summary>
        /// 是否寿控
        /// </summary>
        [DataMember]
        public virtual bool IsLife { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        [DataMember]
        public virtual string State { get; set; }

        /// <summary>
        /// 版本
        /// </summary>
        [DataMember]
        public virtual int Version { get; set; }

        /// <summary>
        /// 上级项号
        /// </summary>
        [DataMember]
        public virtual string NhItemNo { get; set; }

        [DataMember]
        public virtual string Updateby { get; set; }

        [DataMember]
        public virtual DateTime UpdateTime { get; set; }

        [DataMember]
        public virtual CcpLimitDataObjectList CcpLimits { get; set; }

        [DataMember]
        public virtual CcpPnDataObjectList CcpPns { get; set; }

    }

    [CollectionDataContract]
    public class CcpMainDataObjectList : BaseDataObjectList<CcpMainDataObject>
    {
    }

    /// <summary>
    /// CcpMainResultData
    /// </summary>
    [DataContractAttribute(Name = "CcpMainResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (CcpMainResultData))]
    public class CcpMainResultData : ResultData<CcpMainDataObject>
    {
    }

    /// <summary>
    /// CcpMainWithPagination
    /// </summary>
    [KnownType(typeof (CcpMainWithPagination))]
    public class CcpMainWithPagination : BaseDataObjectListWithPagination<CcpMainDataObject>
    {
    }
}
