//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

	/// <summary>
	/// 控制单位
	/// </summary>
    [DataContract(IsReference = false)]
    public partial class IntUnitDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }

        [DataMember]
        public virtual string Unit
		{
			get;
			set;
		}

        [DataMember]
        public virtual string Descritption
		{
			get;
			set;
		}

        [DataMember]
        public virtual string Type
		{
			get;
			set;
		}

        [DataMember]
        public virtual string ShortName
		{
			get;
			set;
		}
	}

    [CollectionDataContract]
    public class IntUnitDataObjectList : BaseDataObjectList<IntUnitDataObject>
    {
    }

    /// <summary>
    /// IntUnitResultData
    /// </summary>
    [DataContractAttribute(Name = "IntUnitResultData", Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof(IntUnitResultData))]
    public class IntUnitResultData : ResultData<IntUnitDataObject>
    {
    }


    /// <summary>
    /// CcpPnWithPagination
    /// </summary>
    [KnownType(typeof(IntUnitWithPagination))]
    public class IntUnitWithPagination : BaseDataObjectListWithPagination<IntUnitDataObject>
    {
    }
}

