//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 滑油添加记录
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class OilAnalysisDataObject
    {

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 飞机号
        /// </summary>
        [DataMember]
        public virtual string AcReg { get; set; }
        /// <summary>
        /// 飞机序列号
        /// </summary>
        [DataMember]
        public virtual string Msn { get; set; }

        /// <summary>
        /// 飞行日期
        /// </summary>
        [DataMember]
        public virtual DateTime FlightDate { get; set; }

        /// <summary>
        /// 航前添加量
        /// </summary>
        [DataMember]
        public virtual decimal Tqsr { get; set; }

        /// <summary>
        /// 航后添加量
        /// </summary>
        [DataMember]
        public virtual decimal Tsr { get; set; }

        /// <summary>
        /// 发动机件号
        /// </summary>
        [DataMember]
        public virtual string Pn { get; set; }

        /// <summary>
        /// 发动机序号
        /// </summary>
        [DataMember]
        public virtual string Sn { get; set; }

        /// <summary>
        /// 章节
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 区域
        /// </summary>
        [DataMember]
        public virtual string Zone { get; set; }

        /// <summary>
        /// 安装位置
        /// </summary>
        [DataMember]
        public virtual string Position { get; set; }

        /// <summary>
        /// TSN
        /// </summary>
        [DataMember]
        public virtual decimal? Toc { get; set; }

        /// <summary>
        /// Csn
        /// </summary>
        [DataMember]
        public virtual decimal? Tocn { get; set; }
        /// <summary>
        /// fh
        /// </summary>
        [DataMember]
        public virtual decimal? Ioc { get; set; }

        /// <summary>
        /// fh
        /// </summary>
        [DataMember]
        public virtual decimal? Ioca { get; set; }

        /// <summary>
        /// cy
        /// </summary>
        [DataMember]
        public virtual decimal? Iocn { get; set; }

        /// <summary>
        /// 3天滚动累积消耗率
        /// </summary>
        [DataMember]
        public virtual decimal? Aoc3 { get; set; }
        /// <summary>
        /// 7天滚动累积消耗率
        /// </summary>
        [DataMember]
        public virtual decimal? Aoc7 { get; set; }

        /// <summary>
        /// n天滚动累积消耗率
        /// </summary>
        [DataMember]
        public virtual decimal? Aocn { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [DataMember]
        public virtual string Notes { get; set; }
        /// <summary>
        /// 警告
        /// </summary>
        [DataMember]
        public virtual string WarnTag { get; set; }
         
    }

    /// <summary>
    /// OilAnalysisDataObjectList
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [CollectionDataContractAttribute(Name = "OilAnalysisDataObjectList", ItemName = "OilAnalysisDataObject", Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    public class OilAnalysisDataObjectList : BaseDataObjectList<OilAnalysisDataObject>
    {
    }

    /// <summary>
    /// OilAnalysisResultData
    /// </summary>
    [DataContractAttribute(Name = "OilAnalysisResultData", Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof(OilAnalysisResultData))]
    public class OilAnalysisResultData : ResultData<OilAnalysisDataObject>
    {
    }

    /// <summary>
    /// OilAnalysisWithPagination
    /// </summary>
    [KnownType(typeof(OilAnalysisWithPagination))]
    public class OilAnalysisWithPagination : BaseDataObjectListWithPagination<OilAnalysisDataObject>
    {
    }
}
