//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 滑油添加记录
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class OilHistoryDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 飞机号
        /// </summary>
        [DataMember]
        public virtual string AcReg { get; set; }
        /// <summary>
        /// 飞机序列号
        /// </summary>
        [DataMember]
        public virtual string Msn { get; set; }

        /// <summary>
        /// 飞行日期
        /// </summary>
        [DataMember]
        public virtual DateTime FlightDate { get; set; }

        /// <summary>
        /// 飞行日志号
        /// </summary>
        [DataMember]
        public virtual string FlLogno { get; set; }

        /// <summary>
        /// 航段号
        /// </summary>
        [DataMember]
        public virtual string FlLegno { get; set; }

        /// <summary>
        /// 航前添加量
        /// </summary>
        [DataMember]
        public virtual decimal UpliftDer { get; set; }

        /// <summary>
        /// 航后添加量
        /// </summary>
        [DataMember]
        public virtual decimal UpliftArr { get; set; }

        /// <summary>
        /// 发动机件号
        /// </summary>
        [DataMember]
        public virtual string Pn { get; set; }

        /// <summary>
        /// 发动机序号
        /// </summary>
        [DataMember]
        public virtual string Sn { get; set; }

        /// <summary>
        /// 章节
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 区域
        /// </summary>
        [DataMember]
        public virtual string Zone { get; set; }

        /// <summary>
        /// 安装位置
        /// </summary>
        [DataMember]
        public virtual string Position { get; set; }

        /// <summary>
        /// TSN
        /// </summary>
        [DataMember]
        public virtual decimal Tsn { get; set; }

        /// <summary>
        /// Csn
        /// </summary>
        [DataMember]
        public virtual decimal Csn { get; set; }
        /// <summary>
        /// fh
        /// </summary>
        [DataMember]
        public virtual decimal Fh { get; set; }

        /// <summary>
        /// cy
        /// </summary>
        [DataMember]
        public virtual decimal Cy { get; set; }
        /// <summary>
        /// 飞行日期
        /// </summary>
        [DataMember]
        public virtual DateTime UpdateDate { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [DataMember]
        public virtual string Notes { get; set; }

        /// <summary>
        /// 最近一次安装日期
        /// </summary>
        [DataMember]
        public virtual string InstalDate { get; set; }

    }

    /// <summary>
    /// CcpPnDataObjectList
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [CollectionDataContractAttribute(Name = "OilHistoryDataObjectList", ItemName = "OilHistoryDataObject", Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    public class OilHistoryDataObjectList : BaseDataObjectList<OilHistoryDataObject>
    {
    }

    /// <summary>
    /// OilHistoryResultData
    /// </summary>
    [DataContractAttribute(Name = "OilHistoryResultData",Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (OilHistoryResultData))]
    public class OilHistoryResultData : ResultData<OilHistoryDataObject>
    {
    }

    /// <summary>
    /// OilHistoryWithPagination
    /// </summary>
    [KnownType(typeof (OilHistoryWithPagination))]
    public class OilHistoryWithPagination : BaseDataObjectListWithPagination<OilHistoryDataObject>
    {
    }
}
