//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 
//     如果重新生成代码，将丢失对此文件所做的更改。 
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 件号
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class PnRegDataObject
    {
        public PnRegDataObject()
        {
            //this.CcpPns = new CcpPnDataObjectList();
        }

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 厂家件号
        /// </summary>
        [DataMember]
        public virtual string Pn { get; set; }

        /// <summary>
        /// 件号类型
        /// </summary>
        [DataMember]
        public virtual string PnClass { get; set; }

        /// <summary>
        /// 章节
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 首选供应商
        /// </summary>
        [DataMember]
        public virtual string Vendor { get; set; }

        /// <summary>
        /// 更新时间
        /// </summary>
        [DataMember]
        public virtual DateTime UpdateTime { get; set; }

        /// <summary>
        /// 更新人
        /// </summary>
        [DataMember]
        public virtual string Updateby { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        [DataMember]
        public virtual string State { get; set; }

        /// <summary>
        /// 规范件号
        /// </summary>
        [DataMember]
        public virtual string SpecPn { get; set; }

        /// <summary>
        /// 是否寿控
        /// </summary>
        [DataMember]
        public virtual bool IsLife { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [DataMember]
        public virtual string Description { get; set; }

        /// <summary>
        /// 转化率
        /// </summary>
        [DataMember]
        public virtual int? TrainRate { get; set; }

        /// <summary>
        /// 发动机EGT裕度下限
        /// </summary>
        [DataMember]
        public virtual decimal? EGTLimit { get; set; }

        /// <summary>
        /// AOC3
        /// </summary>
        [DataMember]
        public virtual decimal? AOC3
        {
            get;
            set;
        }
        /// <summary>
        /// AOC7
        /// </summary>
        [DataMember]
        public virtual decimal? AOC7
        {
            get;
            set;
        }
        /// <summary>
        /// IOC
        /// </summary>
        [DataMember]
        public virtual decimal? IOC
        {
            get;
            set;
        }
        /// <summary>
        /// IOCA
        /// </summary>
        [DataMember]
        public virtual decimal? IOCA
        {
            get;
            set;
        }
        //[DataMember]
        //public virtual CcpPnDataObjectList CcpPns
        //{
        //    get;
        //    set;
        //}

    }

    [CollectionDataContract]
    public class PnRegDataObjectList : BaseDataObjectList<PnRegDataObject>
    {
    }

    /// <summary>
    /// PnRegResultData
    /// </summary>
    //[DataContractAttribute(Name = "PnRegResultData",
    //    Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (PnRegResultData))]
    public class PnRegResultData : ResultData<PnRegDataObject>
    {
    }

    /// <summary>
    /// PnRegWithPagination
    /// </summary>
    //[DataContractAttribute(Name = "PnRegWithPagination",
    //   Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof(PnRegWithPagination))]
    public class PnRegWithPagination : BaseDataObjectListWithPagination<PnRegDataObject>
    {
    }
}

