//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// SCN飞机
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class ScnAcorderDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        [DataMember]
        public virtual string AcOrder { get; set; }

        [DataMember]
        public virtual string AcOrderItem { get; set; }

        [DataMember]
        public virtual string Notes { get; set; }

        /// <summary>
        /// ScnMain外键
        /// </summary>
        [DataMember]
        public virtual int ScnMainID { get; set; }

        /// <summary>
        /// Scn价格
        /// </summary>
        [DataMember]
        public virtual decimal? Price
        {
            get;
            set;
        }

        /// <summary>
        /// MSN
        /// </summary>
        [DataMember]
        public virtual string MSN { get; set; }

        /// <summary>
        /// 批次
        /// </summary>
        [DataMember]
        public virtual string CSCNumber
        {
            get;
            set;
        }

        //[DataMember]
        //public ScnMainDataObject ScnMain
        //{
        //    get;
        //    set;
        //}

    }


    [CollectionDataContract]
    public class ScnAcorderDataObjectList : BaseDataObjectList<ScnAcorderDataObject>
    {
    }

    /// <summary>
    /// ScnAcorderResultData
    /// </summary>
    [DataContractAttribute(Name = "ScnAcorderResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (ScnAcorderResultData))]
    public class ScnAcorderResultData : ResultData<ScnAcorderDataObject>
    {
    }

    /// <summary>
    /// ScnAcorderWithPagination
    /// </summary>
    [KnownType(typeof (ScnAcorderWithPagination))]
    public class ScnAcorderWithPagination : BaseDataObjectListWithPagination<ScnAcorderDataObject>
    {
    }
}
