//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// SCN明细
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class ScnItemDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 附件项
        /// </summary>
        [DataMember]
        public virtual int ScnMainID { get; set; }

        /// <summary>
        /// 项次
        /// </summary>
        [DataMember]
        public virtual int ItemNo { get; set; }

        /// <summary>
        /// 件号（可空）
        /// </summary>
        [DataMember]
        public virtual int? PnRegID { get; set; }

        /// <summary>
        /// ATA章节
        /// </summary>
        [DataMember]
        public virtual int AtaID { get; set; }

        /// <summary>
        /// ATA章节GUID
        /// </summary>
        [DataMember]
        public virtual Guid AtaGuid { get; set; }

        /// <summary>
        /// 件号
        /// </summary>
        [DataMember]
        public virtual string Pn { get; set; }

        /// <summary>
        /// 产品描述
        /// </summary>
        [DataMember]
        public virtual string Description { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [DataMember]
        public virtual string Vendor { get; set; }

        [DataMember]
        public virtual string Notes { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        [DataMember]
        public virtual int Qty { get; set; }

        /// <summary>
        /// 单价
        /// </summary>
        [DataMember]
        public virtual decimal Price { get; set; }

        /// <summary>
        /// 总价
        /// </summary>
        [DataMember]
        public virtual decimal TotalPrice { get; set; }

        /// <summary>
        /// 币种
        /// </summary>
        [DataMember]
        public virtual string Currency { get; set; }

        //[DataMember]
        //public ScnMainDataObject ScnMain
        //{
        //    get;
        //    set;
        //}
    }

    [CollectionDataContract]
    public class ScnItemDataObjectList : BaseDataObjectList<ScnItemDataObject>
    {
    }

    /// <summary>
    /// ScnItemResultData
    /// </summary>
    [DataContractAttribute(Name = "ScnItemResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (ScnItemResultData))]
    public class ScnItemResultData : ResultData<ScnItemDataObject>
    {
    }

    /// <summary>
    /// ScnItemWithPagination
    /// </summary>
    [KnownType(typeof (ScnItemWithPagination))]
    public class ScnItemWithPagination : BaseDataObjectListWithPagination<ScnItemDataObject>
    {
    }
}

