//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 序号件历史时间
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class SnHistoryUnitDataObject
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// 部件历史ID
        /// </summary>
        [DataMember]
        public virtual int SnHistoryID { get; set; }

        /// <summary>
        /// 控制单位ID
        /// </summary>
        [DataMember]
        public virtual string Unit { get; set; }

        /// <summary>
        /// 总计
        /// </summary>
        [DataMember]
        public virtual Decimal USO { get; set; }

        /// <summary>
        /// 备用1
        /// </summary>
        [DataMember]
        public virtual Decimal USN { get; set; }

        /// <summary>
        /// 备用2
        /// </summary>
        [DataMember]
        public virtual Decimal USR { get; set; }

        /// <summary>
        /// 备用2
        /// </summary>
        [DataMember]
        public virtual Decimal USI { get; set; }

        //[DataMember]
        //public virtual SnHistoryDataObject SnHistory
        //{
        //    get;
        //    set;
        //}

    }

    [CollectionDataContract]
    public class SnHistoryUnitDataObjectList : BaseDataObjectList<SnHistoryUnitDataObject>
    {
    }

    /// <summary>
    /// SnHistoryUnitResultData
    /// </summary>
    [DataContractAttribute(Name = "SnHistoryUnitResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (SnHistoryUnitResultData))]
    public class SnHistoryUnitResultData : ResultData<SnHistoryUnitDataObject>
    {
    }

    /// <summary>
    /// SnHistoryUnitWithPagination
    /// </summary>
    [KnownType(typeof (SnHistoryUnitWithPagination))]
    public class SnHistoryUnitWithPagination : BaseDataObjectListWithPagination<SnHistoryUnitDataObject>
    {
    }
}
