//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 
//     如果重新生成代码，将丢失对此文件所做的更改。 
// </auto-generated>
//------------------------------------------------------------------------------
namespace UniCloud.DataObjects
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// 序号件
    /// </summary>
    [DataContract(IsReference = false)]
    public partial class SnRegDataObject
    {
        public SnRegDataObject()
        {
            this.EgtMargins = new EgtMarginDataObjectList();
            this.AttactDocuments = new AttactDocumentDataObjectList();
        }

        #region 一般属性

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public virtual int ID { get; set; }

        /// <summary>
        /// PN ID
        /// </summary>
        [DataMember]
        public virtual int PnRegID { get; set; }

        /// <summary>
        /// 序号
        /// </summary>
        [DataMember]
        public virtual string Sn { get; set; }

        /// <summary>
        /// 飞机ID
        /// </summary>
        [DataMember]
        public virtual string Ac { get; set; }

        /// <summary>
        /// ATAID
        /// </summary>
        [DataMember]
        public virtual string Ata { get; set; }

        /// <summary>
        /// 安装位置描述
        /// </summary>
        [DataMember]
        public virtual string Position { get; set; }

        /// <summary>
        /// 安装日期
        /// </summary>
        [DataMember]
        public virtual DateTime InstallDate { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [DataMember]
        public virtual string Note { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        [DataMember]
        public virtual string Avail { get; set; }

        /// <summary>
        /// 上级序号
        /// </summary>
        [DataMember]
        public virtual int? NhSnRegID { get; set; }

        [DataMember]
        public virtual int? RootSnRegID { get; set; }

        [DataMember]
        public virtual string Zone { get; set; }

        /// <summary>
        /// 推力
        /// </summary>
        [DataMember]
        public virtual string EngineTli { get; set; }

        /// <summary>
        ///  拆下时间
        /// </summary>
        [DataMember]
        public virtual DateTime? RemoveDate { get; set; }

        /// <summary>
        ///  送修时间
        /// </summary>
        [DataMember]
        public virtual DateTime? RepairDate { get; set; }

        /// <summary>
        ///  所有人
        /// </summary>
        [DataMember]
        public virtual string Owner { get; set; }

        /// <summary>
        ///  出租人
        /// </summary>
        [DataMember]
        public virtual string Leaser { get; set; }

        /// <summary>
        ///  属性
        /// </summary>
        [DataMember]
        public virtual string Propertys
        {
            get;
            set;
        }
        /// <summary>
        ///  修理间隔
        /// </summary>
        [DataMember]
        public virtual string Interval
        {
            get;
            set;
        }

        /// <summary>
        /// 是否同步AMASIS Y/N
        /// </summary>
        [DataMember]
        public virtual string SyncAMASIS { get; set; }
        #endregion

        #region 导航属性
        [DataMember]
        public virtual PnRegDataObject PnReg { get; set; }

        [DataMember]
        public virtual SnRegDataObject NhSnReg { get; set; }

        [DataMember]
        public virtual SnRegDataObject RootSnReg { get; set; }

        /// <summary>
        /// EGT裕度
        /// </summary>
        [DataMember]
        public virtual EgtMarginDataObjectList EgtMargins
        {
            get;
            set;
        }

        #endregion

        //-----------------------------------------------------------扩展属性
    }

    #region 集合类

    [CollectionDataContract]
    public class SnRegDataObjectList : BaseDataObjectList<SnRegDataObject>
    {
    }
    
    /// <summary>
    /// SnRegResultData
    /// </summary>
    [DataContractAttribute(Name = "SnRegResultData",
        Namespace = "http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [KnownType(typeof (SnRegResultData))]
    public class SnRegResultData : ResultData<SnRegDataObject>
    {
    }

    /// <summary>
    /// SnRegWithPagination
    /// </summary>
    [KnownType(typeof (SnRegWithPagination))]
    public class SnRegWithPagination : BaseDataObjectListWithPagination<SnRegDataObject>
    {
    }

     #endregion
}

