// <auto-generated />
namespace UniCloud.Domain.Repositories.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOpratetor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOpratetor));
        
        string IMigrationMetadata.Id
        {
            get { return "201308300109427_AddOpratetor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
