// <auto-generated />
namespace UniCloud.Domain.Repositories.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "201308300846413_AddOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
