//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Component.Server.UnitTest.DocService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DocumentTypeDataObjectList", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects", ItemName="DocumentTypeDataObject")]
    [System.SerializableAttribute()]
    public class DocumentTypeDataObjectList : System.Collections.Generic.List<UniCloud.Component.Server.UnitTest.DocService.DocumentTypeDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypeDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class DocumentTypeDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class FaultData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FullMessage {
            get {
                return this.FullMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FullMessageField, value) != true)) {
                    this.FullMessageField = value;
                    this.RaisePropertyChanged("FullMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class Pagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.SortOrder SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortPredicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.SortOrder SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortPredicate {
            get {
                return this.SortPredicateField;
            }
            set {
                if ((object.ReferenceEquals(this.SortPredicateField, value) != true)) {
                    this.SortPredicateField = value;
                    this.RaisePropertyChanged("SortPredicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOrder", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    public enum SortOrder : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descending = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultData_OfficialDocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectListByPage))]
    public partial class ResultData_OfficialDocumentDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.BaseOfficialDocumentDataObjectList BaseDataObjectListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.Pagination PaginationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.BaseOfficialDocumentDataObjectList BaseDataObjectList {
            get {
                return this.BaseDataObjectListField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseDataObjectListField, value) != true)) {
                    this.BaseDataObjectListField = value;
                    this.RaisePropertyChanged("BaseDataObjectList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.Pagination Pagination {
            get {
                return this.PaginationField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginationField, value) != true)) {
                    this.PaginationField = value;
                    this.RaisePropertyChanged("Pagination");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDataOfficialDocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class ResultDataOfficialDocumentDataObject : UniCloud.Component.Server.UnitTest.DocService.ResultData_OfficialDocumentDataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficialDocumentDataObjectListByPage", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class OfficialDocumentDataObjectListByPage : UniCloud.Component.Server.UnitTest.DocService.ResultData_OfficialDocumentDataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="BaseOfficialDocumentDataObjectList", Namespace="http://www.UniCloud.com/CollectionDataObjectList.xsd", ItemName="BaseItem")]
    [System.SerializableAttribute()]
    public class BaseOfficialDocumentDataObjectList : System.Collections.Generic.List<UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficialDocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class OfficialDocumentDataObject : UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObject))]
    public partial class DocumentDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbstractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentFileStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DocumentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject ParentDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject[] SubDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UploaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abstract {
            get {
                return this.AbstractField;
            }
            set {
                if ((object.ReferenceEquals(this.AbstractField, value) != true)) {
                    this.AbstractField = value;
                    this.RaisePropertyChanged("Abstract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentFileStream {
            get {
                return this.DocumentFileStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentFileStreamField, value) != true)) {
                    this.DocumentFileStreamField = value;
                    this.RaisePropertyChanged("DocumentFileStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentTypeID {
            get {
                return this.DocumentTypeIDField;
            }
            set {
                if ((this.DocumentTypeIDField.Equals(value) != true)) {
                    this.DocumentTypeIDField = value;
                    this.RaisePropertyChanged("DocumentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTypeName {
            get {
                return this.DocumentTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeNameField, value) != true)) {
                    this.DocumentTypeNameField = value;
                    this.RaisePropertyChanged("DocumentTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendType {
            get {
                return this.ExtendTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendTypeField, value) != true)) {
                    this.ExtendTypeField = value;
                    this.RaisePropertyChanged("ExtendType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileContent {
            get {
                return this.FileContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FileContentField, value) != true)) {
                    this.FileContentField = value;
                    this.RaisePropertyChanged("FileContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject ParentDocument {
            get {
                return this.ParentDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentDocumentField, value) != true)) {
                    this.ParentDocumentField = value;
                    this.RaisePropertyChanged("ParentDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject[] SubDocuments {
            get {
                return this.SubDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubDocumentsField, value) != true)) {
                    this.SubDocumentsField = value;
                    this.RaisePropertyChanged("SubDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName {
            get {
                return this.UnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNameField, value) != true)) {
                    this.UnitNameField = value;
                    this.RaisePropertyChanged("UnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uploader {
            get {
                return this.UploaderField;
            }
            set {
                if ((object.ReferenceEquals(this.UploaderField, value) != true)) {
                    this.UploaderField = value;
                    this.RaisePropertyChanged("Uploader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardDocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class StandardDocumentDataObject : UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OfficialDocumentDataObjectList", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects", ItemName="OfficialDocumentDataObject")]
    [System.SerializableAttribute()]
    public class OfficialDocumentDataObjectList : System.Collections.Generic.List<UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StandardDocumentDataObjectList", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects", ItemName="StandardDocumentDataObject")]
    [System.SerializableAttribute()]
    public class StandardDocumentDataObjectList : System.Collections.Generic.List<UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultData_StandardDocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectListByPage))]
    public partial class ResultData_StandardDocumentDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.BaseStandardDocumentDataObjectList BaseDataObjectListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniCloud.Component.Server.UnitTest.DocService.Pagination PaginationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.BaseStandardDocumentDataObjectList BaseDataObjectList {
            get {
                return this.BaseDataObjectListField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseDataObjectListField, value) != true)) {
                    this.BaseDataObjectListField = value;
                    this.RaisePropertyChanged("BaseDataObjectList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniCloud.Component.Server.UnitTest.DocService.Pagination Pagination {
            get {
                return this.PaginationField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginationField, value) != true)) {
                    this.PaginationField = value;
                    this.RaisePropertyChanged("Pagination");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDataStandardDocumentDataObject", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class ResultDataStandardDocumentDataObject : UniCloud.Component.Server.UnitTest.DocService.ResultData_StandardDocumentDataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardDocumentDataObjectListByPage", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
    [System.SerializableAttribute()]
    public partial class StandardDocumentDataObjectListByPage : UniCloud.Component.Server.UnitTest.DocService.ResultData_StandardDocumentDataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="BaseStandardDocumentDataObjectList", Namespace="http://www.UniCloud.com/CollectionDataObjectList.xsd", ItemName="BaseItem")]
    [System.SerializableAttribute()]
    public class BaseStandardDocumentDataObjectList : System.Collections.Generic.List<UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObject> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.UniCloud.com", ConfigurationName="DocService.IDocumentService")]
    public interface IDocumentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetDocumentTypeDataObjectList", ReplyAction="http://www.UniCloud.com/IDocumentService/GetDocumentTypeDataObjectListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetDocumentTypeDataObjectListFaultDataFa" +
            "ult", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.DocumentTypeDataObjectList GetDocumentTypeDataObjectList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetDocumentTypeDataObjectList", ReplyAction="http://www.UniCloud.com/IDocumentService/GetDocumentTypeDataObjectListResponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.DocumentTypeDataObjectList> GetDocumentTypeDataObjectListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/ExistDocumentType", ReplyAction="http://www.UniCloud.com/IDocumentService/ExistDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/ExistDocumentTypeFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        bool ExistDocumentType(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/ExistDocumentType", ReplyAction="http://www.UniCloud.com/IDocumentService/ExistDocumentTypeResponse")]
        System.Threading.Tasks.Task<bool> ExistDocumentTypeAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetPaginationOfficialDocumentDataObject", ReplyAction="http://www.UniCloud.com/IDocumentService/GetPaginationOfficialDocumentDataObjectR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetPaginationOfficialDocumentDataObjectF" +
            "aultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectListByPage GetPaginationOfficialDocumentDataObject(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetPaginationOfficialDocumentDataObject", ReplyAction="http://www.UniCloud.com/IDocumentService/GetPaginationOfficialDocumentDataObjectR" +
            "esponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectListByPage> GetPaginationOfficialDocumentDataObjectAsync(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetAllOfficialDocument", ReplyAction="http://www.UniCloud.com/IDocumentService/GetAllOfficialDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetAllOfficialDocumentFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectList GetAllOfficialDocument();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetAllOfficialDocument", ReplyAction="http://www.UniCloud.com/IDocumentService/GetAllOfficialDocumentResponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectList> GetAllOfficialDocumentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetDocumentDataObjectByDocID", ReplyAction="http://www.UniCloud.com/IDocumentService/GetDocumentDataObjectByDocIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetDocumentDataObjectByDocIDFaultDataFau" +
            "lt", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject GetDocumentDataObjectByDocID(System.Guid docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetDocumentDataObjectByDocID", ReplyAction="http://www.UniCloud.com/IDocumentService/GetDocumentDataObjectByDocIDResponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject> GetDocumentDataObjectByDocIDAsync(System.Guid docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetAllStandardDocument", ReplyAction="http://www.UniCloud.com/IDocumentService/GetAllStandardDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetAllStandardDocumentFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectList GetAllStandardDocument();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetAllStandardDocument", ReplyAction="http://www.UniCloud.com/IDocumentService/GetAllStandardDocumentResponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectList> GetAllStandardDocumentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetPaginationStandardDocumentDataObject", ReplyAction="http://www.UniCloud.com/IDocumentService/GetPaginationStandardDocumentDataObjectR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetPaginationStandardDocumentDataObjectF" +
            "aultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectListByPage GetPaginationStandardDocumentDataObject(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetPaginationStandardDocumentDataObject", ReplyAction="http://www.UniCloud.com/IDocumentService/GetPaginationStandardDocumentDataObjectR" +
            "esponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectListByPage> GetPaginationStandardDocumentDataObjectAsync(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetDocumentFileStream", ReplyAction="http://www.UniCloud.com/IDocumentService/GetDocumentFileStreamResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/GetDocumentFileStreamFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        byte[] GetDocumentFileStream(System.Guid documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/GetDocumentFileStream", ReplyAction="http://www.UniCloud.com/IDocumentService/GetDocumentFileStreamResponse")]
        System.Threading.Tasks.Task<byte[]> GetDocumentFileStreamAsync(System.Guid documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/CommitStandardDocumentDTO", ReplyAction="http://www.UniCloud.com/IDocumentService/CommitStandardDocumentDTOResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/CommitStandardDocumentDTOFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject CommitStandardDocumentDTO(UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject standardDocumentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/CommitStandardDocumentDTO", ReplyAction="http://www.UniCloud.com/IDocumentService/CommitStandardDocumentDTOResponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject> CommitStandardDocumentDTOAsync(UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject standardDocumentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/CommitOfficialDocumentDTO", ReplyAction="http://www.UniCloud.com/IDocumentService/CommitOfficialDocumentDTOResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/CommitOfficialDocumentDTOFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject CommitOfficialDocumentDTO(UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject officialDocumentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/CommitOfficialDocumentDTO", ReplyAction="http://www.UniCloud.com/IDocumentService/CommitOfficialDocumentDTOResponse")]
        System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject> CommitOfficialDocumentDTOAsync(UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject officialDocumentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/AddContractDTO", ReplyAction="http://www.UniCloud.com/IDocumentService/AddContractDTOResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniCloud.Component.Server.UnitTest.DocService.FaultData), Action="http://www.UniCloud.com/IDocumentService/AddContractDTOFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/UniCloud.DataObjects")]
        System.Nullable<System.Guid> AddContractDTO(UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UniCloud.com/IDocumentService/AddContractDTO", ReplyAction="http://www.UniCloud.com/IDocumentService/AddContractDTOResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.Guid>> AddContractDTOAsync(UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject document);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceChannel : UniCloud.Component.Server.UnitTest.DocService.IDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.ClientBase<UniCloud.Component.Server.UnitTest.DocService.IDocumentService>, UniCloud.Component.Server.UnitTest.DocService.IDocumentService {
        
        public DocumentServiceClient() {
        }
        
        public DocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.DocumentTypeDataObjectList GetDocumentTypeDataObjectList() {
            return base.Channel.GetDocumentTypeDataObjectList();
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.DocumentTypeDataObjectList> GetDocumentTypeDataObjectListAsync() {
            return base.Channel.GetDocumentTypeDataObjectListAsync();
        }
        
        public bool ExistDocumentType(string name) {
            return base.Channel.ExistDocumentType(name);
        }
        
        public System.Threading.Tasks.Task<bool> ExistDocumentTypeAsync(string name) {
            return base.Channel.ExistDocumentTypeAsync(name);
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectListByPage GetPaginationOfficialDocumentDataObject(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination) {
            return base.Channel.GetPaginationOfficialDocumentDataObject(pagination);
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectListByPage> GetPaginationOfficialDocumentDataObjectAsync(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination) {
            return base.Channel.GetPaginationOfficialDocumentDataObjectAsync(pagination);
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectList GetAllOfficialDocument() {
            return base.Channel.GetAllOfficialDocument();
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.OfficialDocumentDataObjectList> GetAllOfficialDocumentAsync() {
            return base.Channel.GetAllOfficialDocumentAsync();
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject GetDocumentDataObjectByDocID(System.Guid docID) {
            return base.Channel.GetDocumentDataObjectByDocID(docID);
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject> GetDocumentDataObjectByDocIDAsync(System.Guid docID) {
            return base.Channel.GetDocumentDataObjectByDocIDAsync(docID);
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectList GetAllStandardDocument() {
            return base.Channel.GetAllStandardDocument();
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectList> GetAllStandardDocumentAsync() {
            return base.Channel.GetAllStandardDocumentAsync();
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectListByPage GetPaginationStandardDocumentDataObject(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination) {
            return base.Channel.GetPaginationStandardDocumentDataObject(pagination);
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.StandardDocumentDataObjectListByPage> GetPaginationStandardDocumentDataObjectAsync(UniCloud.Component.Server.UnitTest.DocService.Pagination pagination) {
            return base.Channel.GetPaginationStandardDocumentDataObjectAsync(pagination);
        }
        
        public byte[] GetDocumentFileStream(System.Guid documentID) {
            return base.Channel.GetDocumentFileStream(documentID);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetDocumentFileStreamAsync(System.Guid documentID) {
            return base.Channel.GetDocumentFileStreamAsync(documentID);
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject CommitStandardDocumentDTO(UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject standardDocumentData) {
            return base.Channel.CommitStandardDocumentDTO(standardDocumentData);
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject> CommitStandardDocumentDTOAsync(UniCloud.Component.Server.UnitTest.DocService.ResultDataStandardDocumentDataObject standardDocumentData) {
            return base.Channel.CommitStandardDocumentDTOAsync(standardDocumentData);
        }
        
        public UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject CommitOfficialDocumentDTO(UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject officialDocumentData) {
            return base.Channel.CommitOfficialDocumentDTO(officialDocumentData);
        }
        
        public System.Threading.Tasks.Task<UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject> CommitOfficialDocumentDTOAsync(UniCloud.Component.Server.UnitTest.DocService.ResultDataOfficialDocumentDataObject officialDocumentData) {
            return base.Channel.CommitOfficialDocumentDTOAsync(officialDocumentData);
        }
        
        public System.Nullable<System.Guid> AddContractDTO(UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject document) {
            return base.Channel.AddContractDTO(document);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.Guid>> AddContractDTOAsync(UniCloud.Component.Server.UnitTest.DocService.DocumentDataObject document) {
            return base.Channel.AddContractDTOAsync(document);
        }
    }
}
